development:
  adapter: mysql2
  host: localhost
  username: root
  password: azerty
  database: benoit
  encoding: utf8
  reconnect: true

production:
  adapter: mysql2
  database: benoit
  username: root
  password: azerty
  host: localhost
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  database: benoit
  username: root
  password: azerty
  host: localhost
  encoding: utf8
  reconnect: true
